POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NWM5ZTg4YjBjNzAwYWQ4YTk5MDFkNWMiLCJpYXQiOjE3MDc4MjUwNzB9.jRBT60VU6hI-9oP-X7RrtkpVv1rZx5T_wuft1AgoxP4

{
    "title": "Blog 1",
    "author": "Author 1",
    "url": "url 1",
    "likes": "0"
}